[package]
name = "hsr-challenge-card"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
mihomo_rs = { git = "https://github.com/yuvlian/mihomo-rs" }
reqwest = "0.12.5"
rusttype = "0.9.3"
tokio = { version = "1.38.0", features = ["full"] }
